trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'Mvc/Mvc.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Mvc/Mvc.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'Mvc/Mvc.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(1e01003a-b580-4209-a0ee-966441afc749)'
    appName: 'AzureServiceBusDemoMvc'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
